"use client";

import { createContext, useContext, useEffect, useState, ReactNode } from "react";

export type Currency = "RUB" | "TJS" | "USD";
export type Lang = "ru" | "tj" | "uz" | "ky" | "en";

// Базовая валюта мок-данных — RUB. Курсы фиксированные (позже из API ЦБ).
const RATES: Record<Currency, number> = { RUB: 1, TJS: 0.115, USD: 0.0108 };
const SYMBOL: Record<Currency, string> = { RUB: "₽", TJS: "смн", USD: "$" };

export const CURRENCIES: { code: Currency; label: string; flag: string; symbol: string; name: string }[] = [
  { code: "RUB", label: "₽ RUB", flag: "🇷🇺", symbol: "₽", name: "Российский рубль" },
  { code: "TJS", label: "смн TJS", flag: "🇹🇯", symbol: "смн", name: "Таджикский сомони" },
  { code: "USD", label: "$ USD", flag: "🇺🇸", symbol: "$", name: "Доллар США" },
];

export const LANGS: { code: Lang; label: string; short: string; flag: string }[] = [
  { code: "ru", label: "Русский", short: "RU", flag: "🇷🇺" },
  { code: "tj", label: "Тоҷикӣ", short: "TJ", flag: "🇹🇯" },
  { code: "uz", label: "O‘zbekcha", short: "UZ", flag: "🇺🇿" },
  { code: "ky", label: "Кыргызча", short: "KY", flag: "🇰🇬" },
  { code: "en", label: "English", short: "EN", flag: "🇬🇧" },
];

interface Ctx {
  currency: Currency;
  setCurrency: (c: Currency) => void;
  lang: Lang;
  setLang: (l: Lang) => void;
  format: (rub: number) => string;
  t: (key: string) => string;
  ready: boolean;
}

const SettingsContext = createContext<Ctx | null>(null);

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [currency, setCurrencyState] = useState<Currency>("RUB");
  const [lang, setLangState] = useState<Lang>("ru");
  const [ready, setReady] = useState(false);

  useEffect(() => {
    const c = localStorage.getItem("currency") as Currency | null;
    const l = localStorage.getItem("lang") as Lang | null;
    if (c && RATES[c] !== undefined) setCurrencyState(c);
    if (l && ["ru", "tj", "uz", "ky", "en"].includes(l)) {
      setLangState(l);
      document.documentElement.lang = l;
    }
    setReady(true);
  }, []);

  const setCurrency = (c: Currency) => {
    setCurrencyState(c);
    localStorage.setItem("currency", c);
  };
  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("lang", l);
    document.documentElement.lang = l;
  };

  const format = (rub: number) => {
    const v = Math.round(rub * RATES[currency]);
    return `${v.toLocaleString("ru-RU")} ${SYMBOL[currency]}`;
  };

  const t = (key: string) => DICT[lang][key] ?? DICT.ru[key] ?? key;

  return (
    <SettingsContext.Provider value={{ currency, setCurrency, lang, setLang, format, t, ready }}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  const ctx = useContext(SettingsContext);
  if (!ctx) throw new Error("useSettings must be used within SettingsProvider");
  return ctx;
}

// Словарь. Покрывает флоу поиск→бронь и шапку/герой главной.
type Dict = Record<string, string>;

const ru: Dict = {
  // nav / common
  "nav.help": "Помощь",
  "common.change": "Изменить",
  "common.passengers": "пас.",
  "common.economy": "эконом",
  "common.back_home": "На главную",
  // hero / form
  "hero.title": "Найдите дешёвые авиабилеты",
  "hero.subtitle": "Сравниваем сотни авиакомпаний и агентств за секунды",
  "form.from": "Откуда",
  "form.to": "Куда",
  "form.depart": "Туда",
  "form.depart_date": "Дата вылета",
  "form.return": "Обратно",
  "form.return_oneway": "В одну сторону",
  "form.passengers": "Пассажиры",
  "form.search": "Найти билеты",
  "form.complex": "Сложный маршрут",
  // search results
  "search.loading": "Ищем лучшие цены…",
  "search.loading_sub": "Сравниваем предложения авиакомпаний",
  "search.found": "Найдено",
  "search.flights_word": "рейсов",
  "search.sort_best": "Сначала лучшие",
  "search.sort_price": "Сначала дешевле",
  "search.sort_duration": "Сначала быстрые",
  "search.sort_baggage": "Сначала с багажом",
  "search.nonstop": "Без пересадок",
  "search.baggage": "С багажом",
  "search.night": "Ночной",
  "search.reset": "Сбросить",
  "search.filters": "Фильтры",
  "search.empty_title": "Ничего не нашлось",
  "search.empty_sub": "Попробуйте смягчить фильтры",
  "search.empty_reset": "Сбросить фильтры",
  "search.show": "Показать",
  // round trip
  "rt.outbound": "Туда",
  "rt.return": "Обратно",
  "rt.pick_outbound": "Выберите рейс туда",
  "rt.pick_return": "Выберите рейс обратно",
  "rt.change": "Изменить",
  "rt.total": "Итого за двоих в обе стороны",
  // filters panel
  "filters.params": "Параметры рейса",
  "filters.night": "Ночной рейс",
  "filters.fastest": "Самый быстрый",
  "filters.baggage_only": "Только с багажом",
  "filters.baggage": "Багаж",
  "filters.baggage_all": "Все варианты",
  "filters.baggage_with": "С багажом",
  "filters.baggage_without": "Без багажа",
  "filters.departure_time": "Время вылета",
  "filters.time_morning": "Утро",
  "filters.time_day": "День",
  "filters.time_evening": "Вечер",
  "filters.time_night": "Ночь",
  "filters.stops": "Пересадки",
  "filters.stops_all": "Все варианты",
  "filters.stops_0": "Без пересадок",
  "filters.stops_1": "До 1 пересадки",
  "filters.stops_2": "До 2 пересадок",
  "filters.price": "Цена",
  "filters.price_from": "от",
  "filters.price_to": "до",
  "filters.duration": "Длительность пути",
  "filters.duration_to": "до",
  "filters.airport_from": "Аэропорт вылета",
  "filters.airport_to": "Аэропорт прилёта",
  "filters.airlines": "Авиакомпании",
  // flight card / modal
  "card.select": "Выбрать",
  "card.per_all": "за всех пассажиров",
  "card.details": "Детали",
  "card.direct": "прямой",
  "card.stops_word": "пересадок",
  "modal.transfer_in": "Пересадка в городе",
  "modal.smart": "смарт-пересадка",
  "modal.local_time": "В билете указано местное время отправления и прибытия",
  "modal.refund": "Возврат",
  "modal.exchange": "Обмен",
  "modal.yes": "Да",
  "modal.yes_fee": "Да (со штрафом)",
  "modal.no": "Нет",
  "modal.seats": "мест",
  "modal.hand": "Ручная кладь",
  "modal.baggage": "Багаж",
  "modal.no_baggage": "Без багажа",
  // booking
  "book.step_search": "Поиск",
  "book.step_select": "Выбор рейса",
  "book.step_data": "Данные",
  "book.step_pay": "Оплата",
  "book.pax_title": "Данные пассажиров",
  "book.passenger": "Пассажир",
  "book.lastname": "Фамилия (латиницей)",
  "book.firstname": "Имя (латиницей)",
  "book.middlename": "Отчество (если есть)",
  "book.dob": "Дата рождения",
  "book.gender": "Пол",
  "book.male": "Мужской",
  "book.female": "Женский",
  "book.citizenship": "Гражданство",
  "book.doc_number": "Серия и номер паспорта",
  "book.doc_expiry": "Срок действия паспорта",
  "book.contacts": "Контактные данные",
  "book.email": "Email",
  "book.phone": "Телефон",
  "book.contacts_note": "Билет и инструкции по оплате придут на этот email. Телефон — для связи в экстренных случаях.",
  "book.to_payment": "Перейти к оплате",
  "book.total": "Итого",
  "book.tariff": "Тариф",
  "book.fees": "Сборы и налоги",
  "book.agree": "Нажимая кнопку, вы соглашаетесь с условиями использования",
  "book.fix_errors": "Пожалуйста, исправьте:",
  // payment
  "pay.title": "Оплата",
  "pay.method": "Способ оплаты",
  "pay.card": "Банковская карта",
  "pay.sbp": "СБП (быстрые платежи)",
  "pay.installment": "Рассрочка",
  "pay.card_number": "Номер карты",
  "pay.card_holder": "Имя на карте",
  "pay.card_expiry": "Срок",
  "pay.card_cvc": "CVC",
  "pay.pay_now": "Оплатить",
  "pay.secure": "Платёж защищён шифрованием. Данные карты не сохраняются.",
  "pay.back": "Назад к данным",
  "pay.demo": "Демо-режим: реальная оплата не производится.",
  // success
  "ok.title": "Заявка принята!",
  "ok.sub": "Подтверждение придёт на",
};

const tj: Dict = {
  "nav.help": "Кӯмак",
  "common.change": "Тағйир",
  "common.passengers": "мус.",
  "common.economy": "эконом",
  "common.back_home": "Ба саҳифаи асосӣ",
  "hero.title": "Чиптаҳои арзони ҳавоиро ёбед",
  "hero.subtitle": "Садҳо ширкатҳои ҳавоӣ ва агентиҳоро дар сонияҳо муқоиса мекунем",
  "form.from": "Аз куҷо",
  "form.to": "Ба куҷо",
  "form.depart": "Рафтан",
  "form.depart_date": "Санаи парвоз",
  "form.return": "Баргаштан",
  "form.return_oneway": "Як тарафа",
  "form.passengers": "Мусофирон",
  "form.search": "Ҷустуҷӯи чипта",
  "form.complex": "Масири мураккаб",
  "search.loading": "Беҳтарин нархҳоро меҷӯем…",
  "search.loading_sub": "Пешниҳодҳои ширкатҳоро муқоиса мекунем",
  "search.found": "Ёфт шуд",
  "search.sort_best": "Аввал беҳтаринҳо",
  "search.sort_price": "Аввал арзонҳо",
  "search.sort_duration": "Аввал тезҳо",
  "search.sort_baggage": "Аввал бо бағоҷ",
  "search.nonstop": "Бе таваққуф",
  "search.baggage": "Бо бағоҷ",
  "search.night": "Шабона",
  "search.reset": "Аз нав",
  "search.filters": "Филтрҳо",
  "search.empty_title": "Чизе ёфт нашуд",
  "search.empty_sub": "Филтрҳоро нармтар кунед",
  "search.empty_reset": "Тоза кардани филтрҳо",
  "search.show": "Нишон додан",
  "rt.outbound": "Рафтан",
  "rt.return": "Баргаштан",
  "rt.pick_outbound": "Парвози рафтанро интихоб кунед",
  "rt.pick_return": "Парвози баргаштанро интихоб кунед",
  "rt.change": "Тағйир",
  "rt.total": "Ҳамагӣ ба ҳар ду тараф",
  "filters.params": "Параметрҳои парвоз",
  "filters.night": "Парвози шабона",
  "filters.fastest": "Тезтарин",
  "filters.baggage_only": "Танҳо бо бағоҷ",
  "filters.baggage": "Бағоҷ",
  "filters.baggage_all": "Ҳамаи вариантҳо",
  "filters.baggage_with": "Бо бағоҷ",
  "filters.baggage_without": "Бе бағоҷ",
  "filters.departure_time": "Вақти парвоз",
  "filters.time_morning": "Субҳ",
  "filters.time_day": "Рӯз",
  "filters.time_evening": "Шом",
  "filters.time_night": "Шаб",
  "filters.stops": "Таваққуфҳо",
  "filters.stops_all": "Ҳамаи вариантҳо",
  "filters.stops_0": "Бе таваққуф",
  "filters.stops_1": "То 1 таваққуф",
  "filters.stops_2": "То 2 таваққуф",
  "filters.price": "Нарх",
  "filters.price_from": "аз",
  "filters.price_to": "то",
  "filters.duration": "Давомнокии роҳ",
  "filters.duration_to": "то",
  "filters.airport_from": "Фурудгоҳи парвоз",
  "filters.airport_to": "Фурудгоҳи фуруд",
  "filters.airlines": "Ширкатҳои ҳавоӣ",
  "card.select": "Интихоб",
  "card.per_all": "барои ҳама мусофирон",
  "card.details": "Тафсилот",
  "card.direct": "мустақим",
  "card.stops_word": "таваққуф",
  "modal.transfer_in": "Таваққуф дар шаҳри",
  "modal.smart": "смарт-таваққуф",
  "modal.local_time": "Дар чипта вақти маҳаллӣ нишон дода шудааст",
  "modal.refund": "Бозгашт",
  "modal.exchange": "Иваз",
  "modal.yes": "Ҳа",
  "modal.yes_fee": "Ҳа (бо ҷарима)",
  "modal.no": "Не",
  "modal.seats": "ҷой",
  "modal.hand": "Бори дастӣ",
  "modal.baggage": "Бағоҷ",
  "modal.no_baggage": "Бе бағоҷ",
  "book.step_search": "Ҷустуҷӯ",
  "book.step_select": "Интихоби парвоз",
  "book.step_data": "Маълумот",
  "book.step_pay": "Пардохт",
  "book.pax_title": "Маълумоти мусофирон",
  "book.passenger": "Мусофир",
  "book.lastname": "Насаб (бо лотинӣ)",
  "book.firstname": "Ном (бо лотинӣ)",
  "book.middlename": "Номи падар (агар бошад)",
  "book.dob": "Санаи таваллуд",
  "book.gender": "Ҷинс",
  "book.male": "Мард",
  "book.female": "Зан",
  "book.citizenship": "Шаҳрвандӣ",
  "book.doc_number": "Силсила ва рақами шиноснома",
  "book.doc_expiry": "Мӯҳлати шиноснома",
  "book.contacts": "Маълумоти тамос",
  "book.email": "Email",
  "book.phone": "Телефон",
  "book.contacts_note": "Чипта ва дастурҳои пардохт ба ин email меоянд. Телефон — барои тамос дар ҳолатҳои фавқулодда.",
  "book.to_payment": "Гузаштан ба пардохт",
  "book.total": "Ҳамагӣ",
  "book.tariff": "Тариф",
  "book.fees": "Бољ ва андозҳо",
  "book.agree": "Бо пахши тугма шумо бо шартҳои истифода розӣ мешавед",
  "book.fix_errors": "Лутфан ислоҳ кунед:",
  "pay.title": "Пардохт",
  "pay.method": "Тарзи пардохт",
  "pay.card": "Корти бонкӣ",
  "pay.sbp": "СБП (пардохти зуд)",
  "pay.installment": "Қарзи қисматӣ",
  "pay.card_number": "Рақами корт",
  "pay.card_holder": "Ном дар корт",
  "pay.card_expiry": "Мӯҳлат",
  "pay.card_cvc": "CVC",
  "pay.pay_now": "Пардохт",
  "pay.secure": "Пардохт бо рамзгузорӣ ҳифз шудааст. Маълумоти корт нигоҳ дошта намешавад.",
  "pay.back": "Бозгашт ба маълумот",
  "pay.demo": "Реҷаи намоишӣ: пардохти воқеӣ намешавад.",
  "ok.title": "Дархост қабул шуд!",
  "ok.sub": "Тасдиқ меояд ба",
};

const en: Dict = {
  "nav.help": "Help",
  "common.change": "Change",
  "common.passengers": "pax",
  "common.economy": "economy",
  "common.back_home": "Back home",
  "hero.title": "Find cheap flights",
  "hero.subtitle": "We compare hundreds of airlines and agencies in seconds",
  "form.from": "From",
  "form.to": "To",
  "form.depart": "Depart",
  "form.depart_date": "Departure date",
  "form.return": "Return",
  "form.return_oneway": "One way",
  "form.passengers": "Passengers",
  "form.search": "Search flights",
  "form.complex": "Multi-city",
  "search.loading": "Searching for the best prices…",
  "search.loading_sub": "Comparing airline offers",
  "search.found": "Found",
  "search.sort_best": "Best first",
  "search.sort_price": "Cheapest first",
  "search.sort_duration": "Fastest first",
  "search.sort_baggage": "Baggage first",
  "search.nonstop": "Non-stop",
  "search.baggage": "With baggage",
  "search.night": "Night",
  "search.reset": "Reset",
  "search.filters": "Filters",
  "search.empty_title": "Nothing found",
  "search.empty_sub": "Try loosening the filters",
  "search.empty_reset": "Reset filters",
  "search.show": "Show",
  "rt.outbound": "Outbound",
  "rt.return": "Return",
  "rt.pick_outbound": "Choose the outbound flight",
  "rt.pick_return": "Choose the return flight",
  "rt.change": "Change",
  "rt.total": "Total both ways",
  "filters.params": "Flight options",
  "filters.night": "Night flight",
  "filters.fastest": "Fastest",
  "filters.baggage_only": "With baggage only",
  "filters.baggage": "Baggage",
  "filters.baggage_all": "All options",
  "filters.baggage_with": "With baggage",
  "filters.baggage_without": "No baggage",
  "filters.departure_time": "Departure time",
  "filters.time_morning": "Morning",
  "filters.time_day": "Day",
  "filters.time_evening": "Evening",
  "filters.time_night": "Night",
  "filters.stops": "Stops",
  "filters.stops_all": "All options",
  "filters.stops_0": "Non-stop",
  "filters.stops_1": "Up to 1 stop",
  "filters.stops_2": "Up to 2 stops",
  "filters.price": "Price",
  "filters.price_from": "from",
  "filters.price_to": "up to",
  "filters.duration": "Trip duration",
  "filters.duration_to": "up to",
  "filters.airport_from": "Departure airport",
  "filters.airport_to": "Arrival airport",
  "filters.airlines": "Airlines",
  "card.select": "Select",
  "card.per_all": "for all passengers",
  "card.details": "Details",
  "card.direct": "direct",
  "card.stops_word": "stops",
  "modal.transfer_in": "Layover in",
  "modal.smart": "smart layover",
  "modal.local_time": "Local departure and arrival time shown on the ticket",
  "modal.refund": "Refund",
  "modal.exchange": "Exchange",
  "modal.yes": "Yes",
  "modal.yes_fee": "Yes (with fee)",
  "modal.no": "No",
  "modal.seats": "seats",
  "modal.hand": "Hand luggage",
  "modal.baggage": "Baggage",
  "modal.no_baggage": "No baggage",
  "book.step_search": "Search",
  "book.step_select": "Flight",
  "book.step_data": "Details",
  "book.step_pay": "Payment",
  "book.pax_title": "Passenger details",
  "book.passenger": "Passenger",
  "book.lastname": "Last name (Latin)",
  "book.firstname": "First name (Latin)",
  "book.middlename": "Middle name (if any)",
  "book.dob": "Date of birth",
  "book.gender": "Gender",
  "book.male": "Male",
  "book.female": "Female",
  "book.citizenship": "Citizenship",
  "book.doc_number": "Passport number",
  "book.doc_expiry": "Passport expiry",
  "book.contacts": "Contact details",
  "book.email": "Email",
  "book.phone": "Phone",
  "book.contacts_note": "The ticket and payment instructions will be sent to this email. Phone — for emergency contact.",
  "book.to_payment": "Proceed to payment",
  "book.total": "Total",
  "book.tariff": "Fare",
  "book.fees": "Taxes & fees",
  "book.agree": "By clicking the button you agree to the terms of use",
  "book.fix_errors": "Please fix:",
  "pay.title": "Payment",
  "pay.method": "Payment method",
  "pay.card": "Bank card",
  "pay.sbp": "SBP (fast payments)",
  "pay.installment": "Installments",
  "pay.card_number": "Card number",
  "pay.card_holder": "Cardholder name",
  "pay.card_expiry": "Expiry",
  "pay.card_cvc": "CVC",
  "pay.pay_now": "Pay",
  "pay.secure": "Payment is encrypted. Card data is not stored.",
  "pay.back": "Back to details",
  "pay.demo": "Demo mode: no real payment is processed.",
  "ok.title": "Request accepted!",
  "ok.sub": "A confirmation will be sent to",
};

const uz: Dict = {
  ...ru,
  "nav.help": "Yordam",
  "common.change": "O‘zgartirish",
  "common.passengers": "yo‘l.",
  "common.economy": "ekonom",
  "common.back_home": "Bosh sahifaga",
  "hero.title": "Arzon aviachiptalarni toping",
  "hero.subtitle": "Yuzlab aviakompaniya va agentlik takliflarini soniyalarda solishtiramiz",
  "form.from": "Qayerdan",
  "form.to": "Qayerga",
  "form.depart": "Borish",
  "form.return": "Qaytish",
  "form.return_oneway": "Bir tomonga",
  "form.passengers": "Yo‘lovchilar",
  "form.search": "Chiptalarni topish",
  "form.complex": "Murakkab marshrut",
  "search.found": "Topildi",
  "search.sort_best": "Avval eng yaxshilari",
  "search.sort_price": "Avval arzonlari",
  "search.sort_duration": "Avval tezlari",
  "search.sort_baggage": "Avval bagaj bilan",
  "search.nonstop": "To‘g‘ridan-to‘g‘ri",
  "search.baggage": "Bagaj bilan",
  "search.night": "Tungi",
  "search.reset": "Tozalash",
  "search.filters": "Filtrlar",
  "search.empty_title": "Hech narsa topilmadi",
  "search.empty_sub": "Filtrlarni yumshatib ko‘ring",
  "search.empty_reset": "Filtrlarni tozalash",
  "search.show": "Ko‘rsatish",
  "filters.params": "Parvoz parametrlari",
  "filters.fastest": "Eng tez",
  "filters.baggage": "Bagaj",
  "filters.baggage_all": "Barcha variantlar",
  "filters.baggage_with": "Bagaj bilan",
  "filters.baggage_without": "Bagajsiz",
  "filters.departure_time": "Uchish vaqti",
  "filters.time_morning": "Ertalab",
  "filters.time_day": "Kunduzi",
  "filters.time_evening": "Kechqurun",
  "filters.time_night": "Tunda",
  "filters.stops": "To‘xtashlar",
  "filters.stops_all": "Barcha variantlar",
  "filters.stops_0": "To‘g‘ridan-to‘g‘ri",
  "filters.stops_1": "1 tagacha to‘xtash",
  "filters.stops_2": "2 tagacha to‘xtash",
  "filters.price": "Narx",
  "filters.price_from": "dan",
  "filters.price_to": "gacha",
  "filters.duration": "Yo‘l davomiyligi",
  "filters.duration_to": "gacha",
  "filters.airport_from": "Uchish aeroporti",
  "filters.airport_to": "Qo‘nish aeroporti",
  "filters.airlines": "Aviakompaniyalar",
  "card.select": "Tanlash",
};

const ky: Dict = {
  ...ru,
  "nav.help": "Жардам",
  "common.change": "Өзгөртүү",
  "common.passengers": "жүр.",
  "common.economy": "эконом",
  "common.back_home": "Башкы бетке",
  "hero.title": "Арзан авиабилеттерди табыңыз",
  "hero.subtitle": "Жүздөгөн авиакомпания жана агенттиктерди секунд ичинде салыштырабыз",
  "form.from": "Кайдан",
  "form.to": "Кайда",
  "form.depart": "Баруу",
  "form.return": "Кайтуу",
  "form.return_oneway": "Бир тарапка",
  "form.passengers": "Жүргүнчүлөр",
  "form.search": "Билеттерди табуу",
  "form.complex": "Татаал маршрут",
  "search.found": "Табылды",
  "search.sort_best": "Алгач мыктылары",
  "search.sort_price": "Алгач арзандары",
  "search.sort_duration": "Алгач тездери",
  "search.sort_baggage": "Алгач багаж менен",
  "search.nonstop": "Түз каттам",
  "search.baggage": "Багаж менен",
  "search.night": "Түнкү",
  "search.reset": "Тазалоо",
  "search.filters": "Фильтрлер",
  "search.empty_title": "Эч нерсе табылган жок",
  "search.empty_sub": "Фильтрлерди жеңилдетип көрүңүз",
  "search.empty_reset": "Фильтрлерди тазалоо",
  "search.show": "Көрсөтүү",
  "filters.params": "Каттам параметрлери",
  "filters.fastest": "Эң тез",
  "filters.baggage": "Багаж",
  "filters.baggage_all": "Бардык варианттар",
  "filters.baggage_with": "Багаж менен",
  "filters.baggage_without": "Багажсыз",
  "filters.departure_time": "Учуу убактысы",
  "filters.time_morning": "Эртең менен",
  "filters.time_day": "Күндүз",
  "filters.time_evening": "Кечинде",
  "filters.time_night": "Түнкүсүн",
  "filters.stops": "Аялдамалар",
  "filters.stops_all": "Бардык варианттар",
  "filters.stops_0": "Түз каттам",
  "filters.stops_1": "1 аялдамага чейин",
  "filters.stops_2": "2 аялдамага чейин",
  "filters.price": "Баасы",
  "filters.price_from": "баштап",
  "filters.price_to": "чейин",
  "filters.duration": "Жол узактыгы",
  "filters.duration_to": "чейин",
  "filters.airport_from": "Учуу аэропорту",
  "filters.airport_to": "Конуу аэропорту",
  "filters.airlines": "Авиакомпаниялар",
  "card.select": "Тандоо",
};

const DICT: Record<Lang, Dict> = { ru, tj, uz, ky, en };
