"""orders: заявки и пассажиры

Revision ID: 133f1cafa26c
Revises: cd51914f3a72
Create Date: 2026-08-11 22:14:13.291471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133f1cafa26c'
down_revision: Union[str, Sequence[str], None] = 'cd51914f3a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'AWAITING_PAYMENT', 'PAID', 'ISSUED', 'CANCELLED', name='order_status', native_enum=False, length=32), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('depart_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('cabin', sa.String(length=16), nullable=False),
    sa.Column('airline', sa.String(length=8), nullable=True),
    sa.Column('flight_number', sa.String(length=16), nullable=True),
    sa.Column('depart_at', sa.String(length=32), nullable=True),
    sa.Column('arrive_at', sa.String(length=32), nullable=True),
    sa.Column('tariff', sa.String(length=16), nullable=False),
    sa.Column('seat', sa.String(length=8), nullable=True),
    sa.Column('promo', sa.String(length=32), nullable=True),
    sa.Column('payment_method', sa.String(length=16), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('pnr', sa.String(length=16), nullable=True),
    sa.Column('ticket_numbers', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    op.create_index('ix_orders_contact_email', 'orders', ['contact_email'], unique=False)
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=False),
    sa.Column('citizenship', sa.String(length=64), nullable=False),
    sa.Column('doc_number', sa.String(length=32), nullable=False),
    sa.Column('doc_expiry', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passengers_order_id'), 'passengers', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passengers_order_id'), table_name='passengers')
    op.drop_table('passengers')
    op.drop_index('ix_orders_status_created', table_name='orders')
    op.drop_index('ix_orders_contact_email', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
