"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { cabinetData, resendVerification, updateProfile, type AuthUser, type CabinetAlert, type CabinetOrder, type SavedPassenger, type SupportTicket } from "../lib/api";
import { useAuth } from "../context/auth";
import PassportScanButton from "../components/PassportScanButton";
import { nationalityToRussian, type ScannedPassport } from "../lib/passportScan";

const money=(v:number,c:string)=>`${Math.round(v).toLocaleString("ru-RU")} ${c === "RUB" ? "₽" : c}`;
const date=(d:string)=>d.split("-").reverse().join(".");
type Tab="trips"|"passengers"|"alerts"|"support"|"profile";
export default function CabinetDashboard(){
 const {user,loading}=useAuth(); const [tab,setTab]=useState<Tab>("trips"); const [orders,setOrders]=useState<CabinetOrder[]>([]); const [passengers,setPassengers]=useState<SavedPassenger[]>([]); const [alerts,setAlerts]=useState<CabinetAlert[]>([]); const [support,setSupport]=useState<SupportTicket[]>([]); const [error,setError]=useState(""); const [loaded,setLoaded]=useState(false); const [showForm,setShowForm]=useState(false);
 const load=async()=>{try{const [o,p,a,s]=await Promise.all([cabinetData<CabinetOrder[]>("/orders"),cabinetData<SavedPassenger[]>("/passengers"),cabinetData<CabinetAlert[]>("/alerts"),cabinetData<SupportTicket[]>("/support")]);setOrders(o);setPassengers(p);setAlerts(a);setSupport(s);}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить кабинет");}finally{setLoaded(true)}};
 useEffect(()=>{if(user) void load()},[user]);
 if(loading)return <p className="p-10 text-center text-[var(--color-text-muted)]">Загружаем кабинет…</p>;
 if(!user)return <section className="rounded-2xl bg-[var(--color-surface)] p-8 text-center"><h2 className="text-xl font-bold">Войдите в личный кабинет</h2><p className="mt-2 text-sm text-[var(--color-text-muted)]">После входа здесь появятся все поездки, документы и подписки.</p><Link href="/" className="mt-5 inline-block rounded-xl bg-[var(--color-primary)] px-5 py-3 text-sm font-semibold text-white">На главную</Link></section>;
 async function addPassenger(data:Record<string,string>){const clean={...data};for(const k of['middle_name','doc_expiry','gender'])if(!clean[k])delete clean[k];try{await cabinetData("/passengers",{method:"POST",body:JSON.stringify(clean)});setShowForm(false);await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить")}}
 return <div><div className="mb-5 rounded-2xl bg-[var(--color-primary-light)] p-4"><b>{user.fullName || "Путешественник"}</b><span className="ml-2 text-sm text-[var(--color-text-muted)]">{user.email}</span></div>{!user.emailVerified&&<VerifyBanner/>}<div className="mb-5 flex gap-2 overflow-x-auto">{([['trips','Мои поездки'],['passengers','Пассажиры'],['alerts','Подписки на цену'],['support','Поддержка'],['profile','Профиль']] as [Tab,string][]).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-semibold ${tab===id?'bg-[var(--color-primary)] text-white':'border border-[var(--color-border)]'}`}>{label}</button>)}</div>{error&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!loaded?<p className="text-sm text-[var(--color-text-muted)]">Загрузка…</p>:tab==='trips'?<Trips orders={orders}/>:tab==='alerts'?<Alerts items={alerts} reload={load}/>:tab==='support'?<Support items={support}/>:tab==='profile'?<Profile user={user}/>:<Passengers items={passengers} show={showForm} setShow={setShowForm} add={addPassenger} reload={load}/>}</div>
}
const PASSENGER_FIELDS:[string,string][]=[['last_name','Фамилия'],['first_name','Имя'],['middle_name','Отчество'],['dob','Дата рождения'],['citizenship','Гражданство'],['doc_number','Номер документа'],['doc_expiry','Срок действия документа']];
function VerifyBanner(){const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);
 async function resend(){setBusy(true);try{await resendVerification();setSent(true)}finally{setBusy(false)}}
 return <div className="mb-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><b>Подтвердите email.</b> Пока почта не подтверждена, прошлые заявки и подписки на цену, оформленные без входа на этот адрес, не привязываются к аккаунту автоматически. {sent?<span className="font-semibold">Письмо отправлено, проверьте почту.</span>:<button onClick={resend} disabled={busy} className="font-semibold underline disabled:opacity-60">{busy?"Отправляем…":"Отправить письмо ещё раз"}</button>}</div>}
function Trips({orders}:{orders:CabinetOrder[]}){const today=new Date().toISOString().slice(0,10);const upcoming=orders.filter(o=>o.depart_date>=today), past=orders.filter(o=>o.depart_date<today);return <div className="space-y-6"><section><h2 className="mb-3 text-lg font-bold">Ближайшие поездки</h2>{upcoming.length?<div className="space-y-3">{upcoming.map(o=><Trip key={o.ref} order={o}/>)}</div>:<Empty title="Ближайших поездок нет" text="Когда оформите билет, он появится здесь автоматически."/>}</section>{past.length>0&&<section><h2 className="mb-3 text-lg font-bold">Прошедшие поездки</h2>{past.map(o=><Trip key={o.ref} order={o}/>)}</section>}</div>}
function Trip({order:o}:{order:CabinetOrder}){return <Link href={`/account/trips/${o.ref}`} className="block rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-soft)] p-4 transition hover:border-[var(--color-primary)]"><div className="flex justify-between gap-3"><b>{o.origin} → {o.destination}</b><span className="rounded-lg bg-[var(--color-primary-light)] px-2 py-1 text-xs font-semibold text-[var(--color-primary)]">{o.status_label}</span></div><div className="mt-2 text-sm text-[var(--color-text-muted)]">{date(o.depart_date)} · {o.passengers} пассажир(а) · {o.airline||"Авиакомпания уточняется"}</div><div className="mt-3 flex justify-between"><span className="font-mono text-xs">{o.ref}</span><b>{money(o.total_amount,o.currency)}</b></div></Link>}
function Alerts({items,reload}:{items:CabinetAlert[];reload:()=>Promise<void>}){return <div className="space-y-3">{items.length?items.map(a=><div key={a.id} className="rounded-xl border border-[var(--color-border)] p-4"><b>{a.origin} → {a.destination}</b><p className="mt-1 text-sm text-[var(--color-text-muted)]">{date(a.depart_date)} · цель: {money(a.target_price,a.currency)}</p><button onClick={async()=>{await cabinetData(`/alerts/${a.id}`,{method:"DELETE"});await reload()}} className="mt-3 text-sm font-semibold text-red-600">Удалить подписку</button></div>):<Empty title="Подписок пока нет" text="Создайте её на странице поиска — мы сообщим, когда цена снизится."/>}</div>}
function Passengers({items,show,setShow,add,reload}:{items:SavedPassenger[];show:boolean;setShow:(x:boolean)=>void;add:(data:Record<string,string>)=>Promise<void>;reload:()=>Promise<void>}){
 const [form,setForm]=useState<Record<string,string>>({});
 const [editId,setEditId]=useState<number|null>(null);
 const setField=(n:string,v:string)=>setForm(f=>({...f,[n]:v}));
 function onScanned(data:ScannedPassport){setForm(f=>({...f,
  last_name:data.lastName??f.last_name,
  first_name:data.firstName??f.first_name,
  dob:data.dob??f.dob,
  gender:data.sex??f.gender,
  citizenship:nationalityToRussian(data.nationality)??data.nationality??f.citizenship,
  doc_number:data.docNumber??f.doc_number,
  doc_expiry:data.docExpiry??f.doc_expiry,
 }))}
 function startEdit(p:SavedPassenger){
  setEditId(p.id);
  setShow(true);
  setForm({
    last_name:p.last_name, first_name:p.first_name, middle_name:p.middle_name??"",
    dob:p.dob, citizenship:p.citizenship, doc_number:p.doc_number,
    doc_expiry:p.doc_expiry??"", gender:p.gender??"",
  });
 }
 async function save(e:FormEvent){
  e.preventDefault();
  if(editId){
    const clean={...form}; for(const k of['middle_name','doc_expiry','gender']) if(!clean[k]) delete clean[k];
    await cabinetData(`/passengers/${editId}`,{method:"PATCH",body:JSON.stringify(clean)});
    setEditId(null); setShow(false); await reload(); return;
  }
  await add(form);
 }
 return <div>{items.map(p=><div key={p.id} className="mb-3 flex justify-between rounded-xl border border-[var(--color-border)] p-4"><div><b>{p.last_name} {p.first_name}</b><p className="text-sm text-[var(--color-text-muted)]">{p.citizenship} · документ •••• {p.doc_number.slice(-4)}</p></div><div className="flex gap-3"><button type="button" onClick={()=>startEdit(p)} className="text-sm font-semibold text-[var(--color-primary)]">Изменить</button><button type="button" onClick={async()=>{await cabinetData(`/passengers/${p.id}`,{method:"DELETE"});await reload()}} className="text-sm text-red-600">Удалить</button></div></div>)}{!show?<button onClick={()=>{setForm({});setEditId(null);setShow(true)}} className="rounded-xl bg-[var(--color-primary)] px-4 py-3 text-sm font-semibold text-white">Добавить пассажира</button>:<form onSubmit={save} className="mt-4 rounded-xl bg-[var(--color-bg-soft)] p-4"><div className="mb-3"><PassportScanButton onConfirm={onScanned}/></div><div className="grid gap-2 sm:grid-cols-2">{PASSENGER_FIELDS.map(([n,l])=><label key={n} className="text-xs font-semibold">{l}<input value={form[n]||''} onChange={e=>setField(n,e.target.value)} required={!['middle_name','doc_expiry'].includes(n)} type={n==='dob'||n==='doc_expiry'?'date':'text'} className="mt-1 w-full rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-2 text-sm"/></label>)}<label className="text-xs font-semibold">Пол<select value={form.gender||''} onChange={e=>setField('gender',e.target.value)} className="mt-1 w-full rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-2 text-sm"><option value="">Не указан</option><option value="male">Мужской</option><option value="female">Женский</option></select></label></div><button className="mt-3 rounded-lg bg-[var(--color-primary)] p-2 text-sm font-semibold text-white">{editId?"Сохранить изменения":"Сохранить"}</button></form>}</div>
}
function Empty({title,text}:{title:string;text:string}){return <div className="rounded-xl bg-[var(--color-bg-soft)] p-6 text-center"><b>{title}</b><p className="mt-1 text-sm text-[var(--color-text-muted)]">{text}</p></div>}
const SUPPORT_TONE:Record<string,string>={open:'bg-amber-50 text-amber-700',in_progress:'bg-blue-50 text-blue-700',closed:'bg-green-50 text-green-700'};
const SUPPORT_LABEL:Record<string,string>={open:'Открыто',in_progress:'В работе',closed:'Закрыто'};
const SUPPORT_KIND_LABEL:Record<string,string>={question:'Вопрос',refund:'Возврат',exchange:'Обмен'};
function Support({items}:{items:SupportTicket[]}){return items.length?<div className="space-y-3">{items.map(t=><Link key={t.id} href={`/account/trips/${t.order_ref}`} className="block rounded-xl border border-[var(--color-border)] p-4 transition hover:border-[var(--color-primary)]"><div className="flex items-center justify-between gap-3"><b>{SUPPORT_KIND_LABEL[t.kind]} · {t.order_ref}</b><span className={`rounded-lg px-2 py-1 text-xs font-semibold ${SUPPORT_TONE[t.status]}`}>{SUPPORT_LABEL[t.status]}</span></div><p className="mt-2 line-clamp-2 text-sm text-[var(--color-text-muted)]">{t.message}</p>{t.operator_reply&&<p className="mt-2 text-sm text-[var(--color-text)]">Ответ: {t.operator_reply}</p>}<p className="mt-2 text-xs text-[var(--color-text-muted)]">{date(t.created_at.slice(0,10))}</p></Link>)}</div>:<Empty title="Обращений пока нет" text="Написать можно со страницы поездки — там есть форма «Обращение по заявке»."/>}
function Profile({user}:{user:AuthUser}){return <div className="space-y-6"><ProfileName user={user}/><ProfilePassword/><ProfileDanger/></div>}
function ProfileName({user}:{user:AuthUser}){const {updateUser}=useAuth();const [name,setName]=useState(user.fullName??"");const [saving,setSaving]=useState(false);const [msg,setMsg]=useState("");const [err,setErr]=useState("");
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMsg("");setErr("");try{const u=await updateProfile(name||null);updateUser(u);setMsg("Сохранено")}catch(e){setErr(e instanceof Error?e.message:"Не удалось сохранить")}finally{setSaving(false)}}
 return <section className="rounded-xl border border-[var(--color-border)] p-4"><h3 className="text-sm font-bold">Имя</h3><form onSubmit={save} className="mt-3 flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Как вас зовут?" className="min-w-0 flex-1 rounded-lg border border-[var(--color-border)] bg-[var(--color-bg-soft)] px-3 py-2 text-sm"/><button disabled={saving} className="rounded-lg bg-[var(--color-primary)] px-4 text-sm font-semibold text-white disabled:opacity-60">{saving?"…":"Сохранить"}</button></form>{msg&&<p className="mt-2 text-sm text-green-600">{msg}</p>}{err&&<p className="mt-2 text-sm text-red-600">{err}</p>}</section>}
function ProfilePassword(){const [current,setCurrent]=useState("");const [next,setNext]=useState("");const [saving,setSaving]=useState(false);const [msg,setMsg]=useState("");const [err,setErr]=useState("");
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMsg("");setErr("");try{await cabinetData("/profile/password",{method:"POST",body:JSON.stringify({current_password:current||null,new_password:next})});setMsg("Пароль изменён");setCurrent("");setNext("")}catch(e){setErr(e instanceof Error?e.message:"Не удалось сменить пароль")}finally{setSaving(false)}}
 return <section className="rounded-xl border border-[var(--color-border)] p-4"><h3 className="text-sm font-bold">Пароль</h3><form onSubmit={save} className="mt-3 grid gap-2 sm:grid-cols-2"><input type="password" value={current} onChange={e=>setCurrent(e.target.value)} placeholder="Текущий пароль" className="rounded-lg border border-[var(--color-border)] bg-[var(--color-bg-soft)] px-3 py-2 text-sm"/><input required minLength={6} type="password" value={next} onChange={e=>setNext(e.target.value)} placeholder="Новый пароль" className="rounded-lg border border-[var(--color-border)] bg-[var(--color-bg-soft)] px-3 py-2 text-sm"/><button disabled={saving} className="rounded-lg bg-[var(--color-primary)] px-4 py-2 text-sm font-semibold text-white disabled:opacity-60 sm:col-span-2">{saving?"…":"Сменить пароль"}</button></form>{msg&&<p className="mt-2 text-sm text-green-600">{msg}</p>}{err&&<p className="mt-2 text-sm text-red-600">{err}</p>}</section>}
function ProfileDanger(){const {logout}=useAuth();const [password,setPassword]=useState("");const [confirm,setConfirm]=useState(false);const [busy,setBusy]=useState(false);const [err,setErr]=useState("");
 async function del(){setBusy(true);setErr("");try{await cabinetData("/profile/delete",{method:"POST",body:JSON.stringify({password:password||null})});await logout()}catch(e){setErr(e instanceof Error?e.message:"Не удалось удалить аккаунт");setBusy(false)}}
 return <section className="rounded-xl border border-red-200 bg-red-50/40 p-4"><h3 className="text-sm font-bold text-red-700">Удаление аккаунта</h3><p className="mt-1 text-sm text-[var(--color-text-muted)]">Заявки останутся по коду и почте, но доступ из кабинета пропадёт. Действие необратимо.</p>{!confirm?<button onClick={()=>setConfirm(true)} className="mt-3 rounded-lg border border-red-300 px-4 py-2 text-sm font-semibold text-red-700">Удалить аккаунт</button>:<div className="mt-3 flex flex-wrap gap-2"><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Пароль для подтверждения" className="min-w-0 flex-1 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2 text-sm"/><button onClick={del} disabled={busy} className="rounded-lg bg-red-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{busy?"…":"Подтвердить удаление"}</button><button onClick={()=>setConfirm(false)} className="rounded-lg border border-[var(--color-border)] px-4 py-2 text-sm font-semibold">Отмена</button></div>}{err&&<p className="mt-2 text-sm text-red-600">{err}</p>}</section>}
