"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { cabinetData, type CabinetAlert, type CabinetOrder, type SavedPassenger } from "../lib/api";
import { useAuth } from "../context/auth";

const money=(v:number,c:string)=>`${Math.round(v).toLocaleString("ru-RU")} ${c === "RUB" ? "₽" : c}`;
const date=(d:string)=>d.split("-").reverse().join(".");
type Tab="trips"|"passengers"|"alerts";
export default function CabinetDashboard(){
 const {user,loading}=useAuth(); const [tab,setTab]=useState<Tab>("trips"); const [orders,setOrders]=useState<CabinetOrder[]>([]); const [passengers,setPassengers]=useState<SavedPassenger[]>([]); const [alerts,setAlerts]=useState<CabinetAlert[]>([]); const [error,setError]=useState(""); const [loaded,setLoaded]=useState(false); const [showForm,setShowForm]=useState(false);
 const load=async()=>{try{const [o,p,a]=await Promise.all([cabinetData<CabinetOrder[]>("/orders"),cabinetData<SavedPassenger[]>("/passengers"),cabinetData<CabinetAlert[]>("/alerts")]);setOrders(o);setPassengers(p);setAlerts(a);}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить кабинет");}finally{setLoaded(true)}};
 useEffect(()=>{if(user) void load()},[user]);
 if(loading)return <p className="p-10 text-center text-[var(--color-text-muted)]">Загружаем кабинет…</p>;
 if(!user)return <section className="rounded-2xl bg-[var(--color-surface)] p-8 text-center"><h2 className="text-xl font-bold">Войдите в личный кабинет</h2><p className="mt-2 text-sm text-[var(--color-text-muted)]">После входа здесь появятся все поездки, документы и подписки.</p><Link href="/" className="mt-5 inline-block rounded-xl bg-[var(--color-primary)] px-5 py-3 text-sm font-semibold text-white">На главную</Link></section>;
 async function addPassenger(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await cabinetData("/passengers",{method:"POST",body:JSON.stringify(Object.fromEntries(f))});setShowForm(false);await load()}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить")}}
 return <div><div className="mb-5 rounded-2xl bg-[var(--color-primary-light)] p-4"><b>{user.fullName || "Путешественник"}</b><span className="ml-2 text-sm text-[var(--color-text-muted)]">{user.email}</span></div><div className="mb-5 flex gap-2 overflow-x-auto">{([['trips','Мои поездки'],['passengers','Пассажиры'],['alerts','Подписки на цену']] as [Tab,string][]).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-semibold ${tab===id?'bg-[var(--color-primary)] text-white':'border border-[var(--color-border)]'}`}>{label}</button>)}</div>{error&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!loaded?<p className="text-sm text-[var(--color-text-muted)]">Загрузка…</p>:tab==='trips'?<Trips orders={orders}/>:tab==='alerts'?<Alerts items={alerts} reload={load}/>:<Passengers items={passengers} show={showForm} setShow={setShowForm} add={addPassenger} reload={load}/>}</div>
}
function Trips({orders}:{orders:CabinetOrder[]}){const today=new Date().toISOString().slice(0,10);const upcoming=orders.filter(o=>o.depart_date>=today), past=orders.filter(o=>o.depart_date<today);return <div className="space-y-6"><section><h2 className="mb-3 text-lg font-bold">Ближайшие поездки</h2>{upcoming.length?<div className="space-y-3">{upcoming.map(o=><Trip key={o.ref} order={o}/>)}</div>:<Empty title="Ближайших поездок нет" text="Когда оформите билет, он появится здесь автоматически."/>}</section>{past.length>0&&<section><h2 className="mb-3 text-lg font-bold">Прошедшие поездки</h2>{past.map(o=><Trip key={o.ref} order={o}/>)}</section>}</div>}
function Trip({order:o}:{order:CabinetOrder}){return <Link href={`/account/trips/${o.ref}`} className="block rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-soft)] p-4 transition hover:border-[var(--color-primary)]"><div className="flex justify-between gap-3"><b>{o.origin} → {o.destination}</b><span className="rounded-lg bg-[var(--color-primary-light)] px-2 py-1 text-xs font-semibold text-[var(--color-primary)]">{o.status_label}</span></div><div className="mt-2 text-sm text-[var(--color-text-muted)]">{date(o.depart_date)} · {o.passengers} пассажир(а) · {o.airline||"Авиакомпания уточняется"}</div><div className="mt-3 flex justify-between"><span className="font-mono text-xs">{o.ref}</span><b>{money(o.total_amount,o.currency)}</b></div></Link>}
function Alerts({items,reload}:{items:CabinetAlert[];reload:()=>Promise<void>}){return <div className="space-y-3">{items.length?items.map(a=><div key={a.id} className="rounded-xl border border-[var(--color-border)] p-4"><b>{a.origin} → {a.destination}</b><p className="mt-1 text-sm text-[var(--color-text-muted)]">{date(a.depart_date)} · цель: {money(a.target_price,a.currency)}</p><button onClick={async()=>{await cabinetData(`/alerts/${a.id}`,{method:"DELETE"});await reload()}} className="mt-3 text-sm font-semibold text-red-600">Удалить подписку</button></div>):<Empty title="Подписок пока нет" text="Создайте её на странице поиска — мы сообщим, когда цена снизится."/>}</div>}
function Passengers({items,show,setShow,add,reload}:{items:SavedPassenger[];show:boolean;setShow:(x:boolean)=>void;add:(e:FormEvent<HTMLFormElement>)=>void;reload:()=>Promise<void>}){return <div>{items.map(p=><div key={p.id} className="mb-3 flex justify-between rounded-xl border border-[var(--color-border)] p-4"><div><b>{p.last_name} {p.first_name}</b><p className="text-sm text-[var(--color-text-muted)]">{p.citizenship} · документ •••• {p.doc_number.slice(-4)}</p></div><button onClick={async()=>{await cabinetData(`/passengers/${p.id}`,{method:"DELETE"});await reload()}} className="text-sm text-red-600">Удалить</button></div>)}{!show?<button onClick={()=>setShow(true)} className="rounded-xl bg-[var(--color-primary)] px-4 py-3 text-sm font-semibold text-white">Добавить пассажира</button>:<form onSubmit={add} className="mt-4 grid gap-2 rounded-xl bg-[var(--color-bg-soft)] p-4 sm:grid-cols-2">{[['last_name','Фамилия'],['first_name','Имя'],['dob','Дата рождения'],['citizenship','Гражданство'],['doc_number','Номер документа']].map(([n,l])=><label key={n} className="text-xs font-semibold">{l}<input name={n} required type={n==='dob'?'date':'text'} className="mt-1 w-full rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-2 text-sm"/></label>)}<button className="rounded-lg bg-[var(--color-primary)] p-2 text-sm font-semibold text-white">Сохранить</button></form>}</div>}
function Empty({title,text}:{title:string;text:string}){return <div className="rounded-xl bg-[var(--color-bg-soft)] p-6 text-center"><b>{title}</b><p className="mt-1 text-sm text-[var(--color-text-muted)]">{text}</p></div>}
